-- Replace all movie posters with verified TMDB cover art.
UPDATE shows SET poster_url = CASE id
  WHEN 'dune-part-two-m693134' THEN 'https://image.tmdb.org/t/p/original/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg'
  WHEN 'inside-out-2-m1022789' THEN 'https://image.tmdb.org/t/p/original/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg'
  WHEN 'moana-2-m1241982' THEN 'https://image.tmdb.org/t/p/original/aLVkiINlIeCkcZIzb7XHzPYgO6L.jpg'
  WHEN 'barbie-m346698' THEN 'https://image.tmdb.org/t/p/original/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg'
  WHEN 'rebel-ridge-m974602' THEN 'https://image.tmdb.org/t/p/original/doDGKoQzNFBnz0pYol2lkabdmFJ.jpg'
  WHEN 'road-house-m959429' THEN 'https://image.tmdb.org/t/p/original/sH7Orig1yqa6ojMLIzLDxA2GRkH.jpg'
  WHEN 'anyone-but-you-m1072790' THEN 'https://image.tmdb.org/t/p/original/5qHoazZiaLe7oFBok7XlUhg96f2.jpg'
  WHEN 'elemental-m976573' THEN 'https://image.tmdb.org/t/p/original/4Y1WNkd88JXmGfhtWR7dmDAo1T2.jpg'
  WHEN 'wonka-m787699' THEN 'https://image.tmdb.org/t/p/original/qhb1qOilapbapxWQn9jtRCMwXJF.jpg'
  WHEN 'encanto-m568124' THEN 'https://image.tmdb.org/t/p/original/4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg'
  WHEN 'extraction-2-m697843' THEN 'https://image.tmdb.org/t/p/original/7gKI9hpEMcZUQpNgKrkDzJpbnNS.jpg'
  WHEN 'the-idea-of-you-m1010581' THEN 'https://image.tmdb.org/t/p/original/w46Vw536HwNnEzOa7J24YH9DPRS.jpg'
  WHEN 'black-panther-wakanda-forever-m505642' THEN 'https://image.tmdb.org/t/p/original/sv1xJUazXeYqALzczSZ3O6nkH75.jpg'
  WHEN 'guardians-of-the-galaxy-vol-3-m447365' THEN 'https://image.tmdb.org/t/p/original/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg'
  WHEN 'leave-the-world-behind-m1008042' THEN 'https://image.tmdb.org/t/p/original/kdPMUMJzyYAc4roD52qavX0nLIC.jpg'
  WHEN 'air-m966220' THEN 'https://image.tmdb.org/t/p/original/lZOODJzwuQo0etJJyBBZJOSdZcW.jpg'
  WHEN 'glass-onion-m661374' THEN 'https://image.tmdb.org/t/p/original/vDGr1YdrlfbU9wxTOdpf3zChmv9.jpg'
  WHEN 'red-notice-m512195' THEN 'https://image.tmdb.org/t/p/original/lAXONuqg41NwUMuzMiFvicDET9Y.jpg'
  WHEN 'soul-m508442' THEN 'https://image.tmdb.org/t/p/original/6jmppcaubzLF8wkXM36ganVISCo.jpg'
  WHEN 'don-t-look-up-m646385' THEN 'https://image.tmdb.org/t/p/original/nD4M4Bx457ryLuKYpxFwQ2IBJ5w.jpg'
  WHEN 'elvis-m614934' THEN 'https://image.tmdb.org/t/p/original/qBOKWqAFbveZ4ryjJJwbie6tXkQ.jpg'
  WHEN 'luca-m508943' THEN 'https://image.tmdb.org/t/p/original/9x4i9uKGXt8IiiIF5Ey0DIoY738.jpg'
  WHEN 'crazy-rich-asians-m455207' THEN 'https://image.tmdb.org/t/p/original/1XxL4LJ5WHdrcYcihEZUCgNCpAW.jpg'
  WHEN 'turning-red-m508947' THEN 'https://image.tmdb.org/t/p/original/qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg'
  WHEN 'a-star-is-born-m332562' THEN 'https://image.tmdb.org/t/p/original/wrFpXMNBRj2PBiN4Z5kix51XaIZ.jpg'
  WHEN 'free-guy-m550988' THEN 'https://image.tmdb.org/t/p/original/dxraF0qPr1OEgJk17ltQTO84kQF.jpg'
  WHEN 'the-adam-project-m696506' THEN 'https://image.tmdb.org/t/p/original/edKpE9B5qN3e559OuMCLZdW1iBZ.jpg'
  WHEN 'the-color-purple-m872585' THEN 'https://image.tmdb.org/t/p/original/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg'
  WHEN 'the-tomorrow-war-m588228' THEN 'https://image.tmdb.org/t/p/original/34nDCQZwaEvsy4CFO5hkGRFDCVU.jpg'
  WHEN 'aquaman-and-the-lost-kingdom-m572802' THEN 'https://image.tmdb.org/t/p/original/7lTnXOy0iNtBAdRP3TZvaKJ77F6.jpg'
  WHEN 'the-gray-man-m725201' THEN 'https://image.tmdb.org/t/p/original/8cXbitsS6dWQ5gfMTZdorpAAzEH.jpg'
  WHEN 'bird-box-m405774' THEN 'https://image.tmdb.org/t/p/original/rGfGfgL2pEPCfhIvqHXieXFn7gp.jpg'
  WHEN 'sound-of-metal-m519015' THEN 'https://image.tmdb.org/t/p/original/8MaNntHfJPNRPJGSHo4NOmEOvVA.jpg'
  WHEN 'the-flash-m298618' THEN 'https://image.tmdb.org/t/p/original/rktDFPbfHfUbArZ6OOOKsXcv0Bm.jpg'
  WHEN 'it-chapter-two-m474350' THEN 'https://image.tmdb.org/t/p/original/zfE0R94v1E8cuKAerbskfD3VfUt.jpg'
  WHEN 'without-remorse-m460465' THEN 'https://image.tmdb.org/t/p/original/nkayOAUBUu4mMvyNf9iHSUiPjF1.jpg'
  WHEN 'i-want-you-back-m785084' THEN 'https://image.tmdb.org/t/p/original/jQ0gylJMxWSL490sy0RrPj1Lj7e.jpg'
  WHEN 'my-spy-m582566' THEN 'https://image.tmdb.org/t/p/original/t4BtVY9IcGR1k8c3GNYTTLYebOw.jpg'
  WHEN 'coming-2-america-m484718' THEN 'https://image.tmdb.org/t/p/original/nWBPLkqNApY5pgrJFMiI9joSI30.jpg'
  WHEN 'one-night-in-miami-m661542' THEN 'https://image.tmdb.org/t/p/original/exWchxfoLn4gmNZ53vFF4htqkvG.jpg'
  ELSE poster_url
END
WHERE media_type = 'movie';
